#!/usr/bin/env python3
"""
Candle Geometry Analysis for LW-001

This script analyzes the geometric relationships between LW-001 metrics
to determine if the current thresholds describe a mathematically possible
candle type.
"""

import sys
sys.path.insert(0, ".")
sys.path.insert(0, "src")

import numpy as np


def analyze_range_body_relationship():
    """Analyze the relationship between Range and Body."""
    print("=" * 100)
    print("GEOMETRY ANALYSIS: Range vs Body Relationship")
    print("=" * 100)
    
    print("\nGiven:")
    print("  Range = (High - Low) / Open * 100")
    print("  Body = abs(Close - Open) / Open * 100")
    print("  Lower Wick = min(Open, Close) - Low")
    print("  Upper Wick = High - max(Open, Close)")
    print()
    print("  Range = Body + Lower Wick + Upper Wick (all as % of Open)")
    print()
    
    print("Current thresholds:")
    print("  Range >= 6.0%")
    print("  Body >= 1.9%")
    print()
    
    print("Analysis:")
    print("  If Range >= 6.0% and Body >= 1.9%:")
    print("    - Body is at least 31.7% of Range (1.9/6.0)")
    print("    - This leaves 68.3% for wicks (Lower + Upper)")
    print("    - This is geometrically possible")
    print()


def analyze_lw_body_lw_range_relationship():
    """Analyze the relationship between LW/Body and LW/Range."""
    print("=" * 100)
    print("GEOMETRY ANALYSIS: LW/Body vs LW/Range Relationship")
    print("=" * 100)
    
    print("\nGiven:")
    print("  LW/Body = Lower Wick / Body")
    print("  LW/Range = Lower Wick / Range")
    print()
    print("Current thresholds:")
    print("  LW/Body >= 2.5x")
    print("  LW/Range >= 63.0%")
    print()
    
    print("Analysis:")
    print("  If LW/Body >= 2.5x:")
    print("    - Lower Wick >= 2.5 * Body")
    print("    - Lower Wick is at least 2.5x larger than Body")
    print()
    print("  If LW/Range >= 63.0%:")
    print("    - Lower Wick >= 0.63 * Range")
    print("    - Lower Wick is at least 63% of Range")
    print()
    print("  Combining both:")
    print("    - Lower Wick >= 2.5 * Body")
    print("    - Lower Wick >= 0.63 * Range")
    print("    - Therefore: 2.5 * Body <= 0.63 * Range")
    print("    - Therefore: Body <= 0.252 * Range")
    print("    - Therefore: Body <= 25.2% of Range")
    print()
    print("  But we also require:")
    print("    - Body >= 1.9%")
    print("    - Range >= 6.0%")
    print()
    print("  If Range = 6.0% and Body = 1.9%:")
    print("    - Body/Range = 1.9/6.0 = 31.7%")
    print("    - This exceeds the 25.2% limit from LW/Body >= 2.5x and LW/Range >= 63%")
    print()
    print("  CONCLUSION: The combination of:")
    print("    - Range >= 6.0%")
    print("    - Body >= 1.9%")
    print("    - LW/Body >= 2.5x")
    print("    - LW/Range >= 63.0%")
    print("    is GEOMETRICALLY IMPOSSIBLE")
    print()
    print("  Proof:")
    print("    - LW/Body >= 2.5x => Lower Wick >= 2.5 * Body")
    print("    - LW/Range >= 63% => Lower Wick >= 0.63 * Range")
    print("    - Therefore: 2.5 * Body <= 0.63 * Range")
    print("    - Therefore: Body/Range <= 0.252 (25.2%)")
    print("    - But Body >= 1.9% and Range >= 6.0% => Body/Range >= 1.9/6.0 = 0.317 (31.7%)")
    print("    - 31.7% > 25.2% => CONTRADICTION")
    print()


def analyze_open_low_relationship():
    """Analyze the Open->Low relationship."""
    print("=" * 100)
    print("GEOMETRY ANALYSIS: Open->Low Relationship")
    print("=" * 100)
    
    print("\nGiven:")
    print("  Open->Low = (Low - Open) / Open * 100")
    print("  Lower Wick = min(Open, Close) - Low")
    print()
    print("Current threshold:")
    print("  Open->Low <= -5.0%")
    print()
    
    print("Analysis:")
    print("  For a valid LW-001 signal (red candle with long lower wick):")
    print("    - Close < Open (red candle)")
    print("    - min(Open, Close) = Close")
    print("    - Lower Wick = Close - Low")
    print("    - Open->Low = (Low - Open) / Open * 100")
    print()
    print("  If Open->Low <= -5.0%:")
    print("    - Low <= 0.95 * Open")
    print("    - Price drops at least 5% from Open to Low")
    print()
    print("  This is a strong requirement but geometrically possible.")
    print()


def analyze_full_geometry():
    """Analyze the full geometric constraints."""
    print("=" * 100)
    print("FULL GEOMETRY ANALYSIS: All 6 Conditions")
    print("=" * 100)
    
    print("\nCurrent thresholds:")
    print("  1. Range >= 6.0%")
    print("  2. Body >= 1.9%")
    print("  3. LW/Body >= 2.5x")
    print("  4. LW/Range >= 63.0%")
    print("  5. Open->Low <= -5.0%")
    print("  6. Volume Ratio >= 2.6x")
    print()
    
    print("Geometric constraints:")
    print()
    print("From (3) LW/Body >= 2.5x:")
    print("  Lower Wick >= 2.5 * Body")
    print()
    print("From (4) LW/Range >= 63%:")
    print("  Lower Wick >= 0.63 * Range")
    print()
    print("Combining (3) and (4):")
    print("  2.5 * Body <= 0.63 * Range")
    print("  Body/Range <= 0.252 (25.2%)")
    print()
    print("From (1) and (2):")
    print("  Range >= 6.0%")
    print("  Body >= 1.9%")
    print("  Body/Range >= 1.9/6.0 = 0.317 (31.7%)")
    print()
    print("CONTRADICTION:")
    print("  Body/Range must be <= 25.2% (from LW/Body and LW/Range)")
    print("  Body/Range must be >= 31.7% (from Range and Body thresholds)")
    print("  25.2% < 31.7% => IMPOSSIBLE")
    print()
    print("=" * 100)
    print("CONCLUSION: The current thresholds describe a GEOMETRICALLY IMPOSSIBLE candle")
    print("=" * 100)
    print()
    print("The combination of:")
    print("  - Range >= 6.0%")
    print("  - Body >= 1.9%")
    print("  - LW/Body >= 2.5x")
    print("  - LW/Range >= 63.0%")
    print("cannot be satisfied simultaneously by any real candle.")
    print()
    print("This explains why 0 out of 15,000 candles passed all conditions.")
    print()


def calculate_possible_thresholds():
    """Calculate threshold combinations that are geometrically possible."""
    print("=" * 100)
    print("POSSIBLE THRESHOLD COMBINATIONS")
    print("=" * 100)
    
    print("\nTo make the thresholds geometrically possible, we need:")
    print("  Body/Range <= 0.252 (from LW/Body >= 2.5x and LW/Range >= 63%)")
    print()
    print("Option 1: Keep Range >= 6.0%, adjust Body threshold")
    print("  If Range >= 6.0% and Body/Range <= 0.252:")
    print("    Body <= 0.252 * 6.0% = 1.51%")
    print("  Current Body threshold: 1.9%")
    print("  Required adjustment: Body <= 1.51%")
    print()
    print("Option 2: Keep Body >= 1.9%, adjust Range threshold")
    print("  If Body >= 1.9% and Body/Range <= 0.252:")
    print("    Range >= 1.9% / 0.252 = 7.54%")
    print("  Current Range threshold: 6.0%")
    print("  Required adjustment: Range >= 7.54%")
    print()
    print("Option 3: Keep Range >= 6.0% and Body >= 1.9%, adjust LW/Body or LW/Range")
    print("  If Range >= 6.0% and Body >= 1.9%:")
    print("    Body/Range >= 1.9/6.0 = 0.317 (31.7%)")
    print("  To satisfy LW/Body >= X and LW/Range >= Y:")
    print("    We need: X * Body <= Y * Range")
    print("    We need: Body/Range <= Y/X")
    print("    We need: 0.317 <= Y/X")
    print("    We need: Y >= 0.317 * X")
    print()
    print("  If we keep LW/Body >= 2.5x:")
    print("    Y >= 0.317 * 2.5 = 0.792 (79.2%)")
    print("    LW/Range >= 79.2% (instead of 63%)")
    print()
    print("  If we keep LW/Range >= 63%:")
    print("    0.317 >= Y/X")
    print("    X <= Y/0.317 = 0.63/0.317 = 1.99")
    print("    LW/Body >= 1.99x (instead of 2.5x)")
    print()
    print("Option 4: Adjust both LW/Body and LW/Range")
    print("  Example: LW/Body >= 2.0x, LW/Range >= 70%")
    print("    Check: 0.317 <= 0.70/2.0 = 0.35 (35%)")
    print("    This is geometrically possible")
    print()


def main():
    """Run all geometry analyses."""
    analyze_range_body_relationship()
    analyze_lw_body_lw_range_relationship()
    analyze_open_low_relationship()
    analyze_full_geometry()
    calculate_possible_thresholds()
    
    print("=" * 100)
    print("FINAL RECOMMENDATION")
    print("=" * 100)
    print()
    print("The current thresholds are GEOMETRICALLY IMPOSSIBLE.")
    print()
    print("The contradiction is between:")
    print("  - Range >= 6.0% and Body >= 1.9% (requires Body/Range >= 31.7%)")
    print("  - LW/Body >= 2.5x and LW/Range >= 63% (requires Body/Range <= 25.2%)")
    print()
    print("To fix this, one of the following must be adjusted:")
    print("  1. Lower Body threshold from 1.9% to <= 1.51%")
    print("  2. Raise Range threshold from 6.0% to >= 7.54%")
    print("  3. Lower LW/Body threshold from 2.5x to <= 1.99x")
    print("  4. Raise LW/Range threshold from 63% to >= 79.2%")
    print("  5. Combination of the above")
    print()
    print("This is a MATHEMATICAL NECESSITY, not a market observation.")
    print("No amount of data collection will find candles that satisfy")
    print("geometrically impossible conditions.")
    print()


if __name__ == "__main__":
    main()
